"""add feature snapshot tables

Revision ID: 35ed8115c145
Revises: 
Create Date: 2025-12-20 13:03:15.640609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ed8115c145'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('minutes_last_5', sa.Integer(), nullable=False),
    sa.Column('goals_last_5', sa.Integer(), nullable=False),
    sa.Column('assists_last_5', sa.Integer(), nullable=False),
    sa.Column('xg_last_5', sa.Float(), nullable=False),
    sa.Column('xa_last_5', sa.Float(), nullable=False),
    sa.Column('ict_last_5', sa.Float(), nullable=False),
    sa.Column('appearances_last_5', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('opponent_team', sa.String(length=50), nullable=False),
    sa.Column('opponent_difficulty', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_feature_snapshots_gameweek'), 'player_feature_snapshots', ['gameweek'], unique=False)
    op.create_index(op.f('ix_player_feature_snapshots_player_id'), 'player_feature_snapshots', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_feature_snapshots_snapshot_time'), 'player_feature_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_player_feature_snapshots_team_name'), 'player_feature_snapshots', ['team_name'], unique=False)
    op.create_table('team_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('minutes_last_5', sa.Integer(), nullable=False),
    sa.Column('goals_last_5', sa.Integer(), nullable=False),
    sa.Column('assists_last_5', sa.Integer(), nullable=False),
    sa.Column('xg_last_5', sa.Float(), nullable=False),
    sa.Column('xa_last_5', sa.Float(), nullable=False),
    sa.Column('ict_last_5', sa.Float(), nullable=False),
    sa.Column('appearances_last_5', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('opponent_team', sa.String(length=50), nullable=False),
    sa.Column('opponent_difficulty', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_feature_snapshots_gameweek'), 'team_feature_snapshots', ['gameweek'], unique=False)
    op.create_index(op.f('ix_team_feature_snapshots_snapshot_time'), 'team_feature_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_team_feature_snapshots_team_name'), 'team_feature_snapshots', ['team_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_feature_snapshots_team_name'), table_name='team_feature_snapshots')
    op.drop_index(op.f('ix_team_feature_snapshots_snapshot_time'), table_name='team_feature_snapshots')
    op.drop_index(op.f('ix_team_feature_snapshots_gameweek'), table_name='team_feature_snapshots')
    op.drop_table('team_feature_snapshots')
    op.drop_index(op.f('ix_player_feature_snapshots_team_name'), table_name='player_feature_snapshots')
    op.drop_index(op.f('ix_player_feature_snapshots_snapshot_time'), table_name='player_feature_snapshots')
    op.drop_index(op.f('ix_player_feature_snapshots_player_id'), table_name='player_feature_snapshots')
    op.drop_index(op.f('ix_player_feature_snapshots_gameweek'), table_name='player_feature_snapshots')
    op.drop_table('player_feature_snapshots')
    # ### end Alembic commands ###
